// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBc6yuc1Pr9JI2LCiFeGXwMQlUUhalbVA',
    appId: '1:1086489916721:web:55879c1887017d1a06ac10',
    messagingSenderId: '1086489916721',
    projectId: 'food-delivery-ff528',
    authDomain: 'food-delivery-ff528.firebaseapp.com',
    storageBucket: 'food-delivery-ff528.firebasestorage.app',
    measurementId: 'G-QCK7MNPYRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_DzgV2JILIT44hQRtyUqwNMqWC5uRf74',
    appId: '1:1086489916721:android:85cec4c05f73a27106ac10',
    messagingSenderId: '1086489916721',
    projectId: 'food-delivery-ff528',
    storageBucket: 'food-delivery-ff528.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR9SgS86KAhfQpTDahVTKvApN--qxjYQU',
    appId: '1:1086489916721:ios:c6700e4b7457adc106ac10',
    messagingSenderId: '1086489916721',
    projectId: 'food-delivery-ff528',
    storageBucket: 'food-delivery-ff528.firebasestorage.app',
    iosBundleId: 'com.example.restapi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR9SgS86KAhfQpTDahVTKvApN--qxjYQU',
    appId: '1:1086489916721:ios:c6700e4b7457adc106ac10',
    messagingSenderId: '1086489916721',
    projectId: 'food-delivery-ff528',
    storageBucket: 'food-delivery-ff528.firebasestorage.app',
    iosBundleId: 'com.example.restapi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBc6yuc1Pr9JI2LCiFeGXwMQlUUhalbVA',
    appId: '1:1086489916721:web:fd9a93ead4a9503706ac10',
    messagingSenderId: '1086489916721',
    projectId: 'food-delivery-ff528',
    authDomain: 'food-delivery-ff528.firebaseapp.com',
    storageBucket: 'food-delivery-ff528.firebasestorage.app',
    measurementId: 'G-9EGNRVYMTY',
  );
}
